# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.194.3/containers/javascript-node/.devcontainer/base.Dockerfile

# [Choice] Node.js version: 16, 14, 12, 16-bullseye, 14-bullseye, 12-bullseye, 16-buster, 14-buster, 12-buster
ARG VARIANT="12"
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}

USER node

WORKDIR /app

RUN ls
